Fix article script bug
snucse/snucse pull request #46
Opened 2017-03-05 10:26 UTC by Leeingnyo

fixes #14 

`dangerously-set-inner-html` 패키지를 사용하여 본문 속 스크립트 태그가 작동하도록 만들었습니다.

2017-03-06 06:08 UTC, pps789 approved these changes

2017-03-06 06:50 UTC, Leeingnyo commented
프로필 본문도 고쳐야 합니다.

2017-03-13 04:55 UTC, pps789 approved these changes

2017-03-13 15:47 UTC, tirr-c requested changes
Markdown에서 사용한 스크립트 태그는 나타나지 않을 것 같네요.

2017-03-13 15:47 UTC, VBChunguk commented on components/Profile.js
> +    const profileDescriptionView = renderingMode === 'html' ? (
Markdown에서도 `<script>` 태그를 사용할 수 있습니다.

2017-03-15 01:59 UTC, Leeingnyo commented on components/Profile.js
> +    const profileDescriptionView = renderingMode === 'html' ? (
markdown 일 경우, 서버에서 `renderedContent`를 `'`를 `&#39;`로 바꿔서 보내줘서 에러가 나서 이렇게 처리했습니다. 서버 동작을 바꿔야 하는 문제일까요?

2017-03-16 13:36 UTC, VBChunguk commented on components/Profile.js
> +    const profileDescriptionView = renderingMode === 'html' ? (
마크다운에서 `<script>`를 써도 아무 문제가 되지 않긴 한데... 좀 그렇네요. 그냥 이대로 갈까요?

2017-03-16 13:50 UTC, Leeingnyo commented on components/Profile.js
> +    const profileDescriptionView = renderingMode === 'html' ? (
> 마크다운에서 <script>를 써도 아무 문제 없긴 한데...

원래 마크다운이라면 그래야 한다는 말이죠? 그럼 그렇게 고치는게 좋을 것 같아요. 관련 사항을 서버에 얘기해봅시다.

2017-03-26 06:12 UTC, Leeingnyo commented on components/Profile.js
> +    const profileDescriptionView = renderingMode === 'html' ? (
@operatz 도와주세요. 서버에서 markdown 렌더링을 할 때 <script> 내부의 내용을 escape 해서 보내줘서 작동하지 않는 것 같습니다. 사실 어떻게 되는지 모르겠어요, 저는. 처리가 어렵다면 markdown 일 때는 <script> 태그를 지원하지 않는 것으로...

2017-04-02 16:43 UTC, VBChunguk commented on components/Profile.js
> +    const profileDescriptionView = renderingMode === 'html' ? (
이 부분은 서버랑 맞춰서 수정하도록 합시다.

2017-04-02 16:44 UTC, tirr-c approved these changes

2017-04-03 05:47 UTC, pps789 requested changes

2017-04-03 05:47 UTC, pps789 commented on components/Profile.js
> +    return this.props.loading !== props.loading;
`FollowBox`가 올바르게 작동하려면 `props.following`이 변할 때에도 컴포넌트를 업데이트 해야 합니다.

2017-04-03 15:14 UTC, pps789 approved these changes

2017-04-19 14:02 UTC, merged