WIP: Iframe feed
snucse/snucse pull request #66
Opened 2017-03-07 15:15 UTC by Leeingnyo

2017-03-13 15:57 UTC, tirr-c requested changes
왜 전이랑 지금이랑 다르지...?

2017-03-13 15:57 UTC, VBChunguk commented on components/FeedList/FeedArticle.js
> +    iframe.style.height = (doc.scrollingElement || doc.body).scrollHeight + 'px';
`doc.body`를 써도 될 것 같아요... 전에 테스트할 땐 엄청 잘려 보였는데, 지금은 멀쩡하고 오히려 `scrollingElement`를 쓰니까 여백이 너무 남습니다.

2017-03-15 02:59 UTC, Leeingnyo commented
iframe resizer 가 잘 되는지에 대해서 테스트를 잘 해주세요

2017-03-16 13:30 UTC, VBChunguk commented
저의 머지 리퀘스트를 확인해 주십시오...

2017-04-02 16:02 UTC, tirr-c approved these changes

2017-04-19 12:50 UTC, merged