Merge to master
snucse/snucse pull request #68
Opened 2017-03-08 15:31 UTC by dnsdhrj

2017-03-08 16:52 UTC, tirr-c requested changes
3547c88 만 `snucse:master` 위로 리베이스해 주세요. 이미 머지된 커밋이 끼어들어가 있네요.

2017-03-09 05:28 UTC, dnsdhrj commented
수정했습니다.

2017-03-09 06:52 UTC, tirr-c approved these changes
세션 스토리지를 쓰는군요. 어차피 로컬 스토리지를 쓰고 있는 상황이니 저는 문제없다고 봅니다.

2017-03-09 15:42 UTC, operatz commented
저는 URL에서 페이지의 동작이 최대한 드러날 수 있는 방법을 선호하긴 하는데요, (i.e. http://www.snucse.org/login?next=/activities 이런 느낌으로) 이건 취향의 영역인 것 같아 다른 분들의 의견을 들어볼게요

2017-03-13 03:49 UTC, Leeingnyo commented
지저분하다 vs 링크를 통해 정보를 알려준다

저는 아무래도 좋습니다.

2017-03-14 14:42 UTC, operatz commented
지금 방식도 괜찮다는 의견이 많으니 머지할게요

2017-03-14 14:42 UTC, merged