태그 박스 리팩토링
snucse/snucse pull request #88
Opened 2017-03-30 03:41 UTC by Leeingnyo

리팩토링 했습니다. 

### 태그박스 인터페이스

#### 기본

* id: 태그 리스트에 부모가 있을 경우, 부모의 id 입니다. (글의 태그 - >글의 아이디)

#### 태그 추가 관련

* addable: '태그 추가' 활성화 여부, true 일 경우 아래의 property를 넘겨주세요.
* addTag: 태그 추가하는 함수. submit이 일어날 때 target id, tag name 을 받을 것
* candidates: 태그 추가할 때 나타날 자동완성
* loadCandidateTags: 자동완성 불러오는 함수
* initializeCandidateTags: 자동완성 초기화 함수
* getTagFormId: 태그 폼이 여러 곳에 나타날 수 있으니 각 태그 폼에 고유한 아이디를 부여합니다.

#### 태그 삭제 관련

* deletable: 삭제 가능 여부. x 버튼이 뜹니다. true 일 경우 아래의 property를 넘겨주세요.
* deleteTag: 태그 삭제하는 함수. submit이 일어날 때 target id, tag name을 받을 것

#### 태그 정보

* tags: 보여질 태그입니다. `{ tag object }`를 array로 주세요.

#### 접근 가능 여부

* accessible: 태그 링크 활성화 입니다 (해당 태그로 가는 링크). 현재는 등급에 따라 나누고 있습니다.

### 기타

* 새내기회원에게 보여지는 태그 글자크기가 달라서 수정했습니다.
* `UserLevel`에 `tagAccessible()` 을 추가했습니다.

2017-04-02 14:49 UTC, pps789 requested changes

2017-04-02 14:49 UTC, pps789 commented on components/boxes/TagBox/ArticleTagBox.js
> +    deleteTagToArticle: (articleId, tagName) => deleteTagToArticle(dispatch, articleId, tagName),
`deleteTagToArticle`보단 `deleteTagFromArticle`이 좋을 것 같습니다.

2017-04-02 15:51 UTC, VBChunguk commented on components/boxes/TagBox/ArticleTagBox.js
> +    deleteTagToArticle: (articleId, tagName) => deleteTagToArticle(dispatch, articleId, tagName),
`actions/dispatchers/tagDispatchers.js`에 있는 대로 간 것 같은데, 이게 커밋된 건 꽤 오래되었네요...

2017-04-03 00:56 UTC, pps789 approved these changes

2017-04-03 15:38 UTC, tirr-c approved these changes

2017-04-06 13:23 UTC, merged